name: sitm remote ci check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  sitm-scan:
    runs-on: ubuntu-latest
    name: Remote Code Scan (SiTM)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install SiTM and dependencies
        run: |
          pip install -e .  # assumes sitm uses setup.py/setup.cfg
          pip install -r requirements.txt

      - name: Run credential scan (dance_call)
        run: |
          echo "🔍 Running credential scan..."
          python3 sitm_core/inference/dance_call.py .

      - name: Run function-level vuln scan (vulstyle_call)
        run: |
          echo "🔍 Running function-level scan..."
          python3 sitm_core/inference/vulstyle_call.py .

      - name: Fail if issues were found
        if: failure()
        run: |
          echo "❌ SiTM detected issues. Blocking merge."
          exit 1
